package com.ecommerceapp.navigation

enum class AppScreenName {
    SPLASH,
    SIGNIN, SIGNUP, FORGETPASSWORD, CHANGEPASSWORD, PROFILE,
    HOME,
    CART, ADDRESS, TIMESLOT, OFFER, PAYMENT, SUCCESS,
    MYORDER,
    SEARCH, FILTER,
    ABOUTUS, CONTACTUS, TERMS, PRIVACY, SETTINGS, FEEDBACK;
}