package com.ecommerceapp.navigation

enum class AppScreenName {
    SPLASH,
    SIGNIN, SIGNUP, FORGETPASSWORD, CHANGEPASSWORD, PROFILE,
    HOME,
    CART, ADDRESS, TIMESLOT, OFFERS, PAYMENT, SUCCESS,
    MY_ORDERS,
    SEARCH, FILTER,
    ABOUT_US, CONTACT_US, TERMS_AND_CONDITIONS, PRIVACY_POLICY, SETTINGS, FEEDBACK,
    ADDEDITADDRESS,RATING,VERIFYOTP,LOGOUT,
    MY_WALLET,MY_FAVORITE_CARTS;
}